name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Start services with docker-compose
      - name: Run docker-compose
        run: |
          docker compose up -d
          sleep 15   # give services time to start

      # Step 4: Check if containers are running
      - name: Verify running containers
        run: docker ps -a

      # Step 5: Run simple test (e.g., check Nginx response)
      - name: Test web service
        run: curl -v http://localhost:8080 || exit 1

      # Step 6: Tear down
      - name: Shut down services
        if: always()
        run: docker compose down -v
